# Generated by Django 4.2.7 on 2025-12-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video havolasi (masalan: https://www.youtube.com/watch?v=xxxxx)', max_length=500, null=True, verbose_name='Video (YouTube link)'),
        ),
    ]
